version: '3'

services:
  postgis:
    image: kartoza/postgis:10.0-2.4

  triplifier:
    image: bregalia/usgs-triplifier
    environment:
      - PGUSER=docker
      - PGPASSWORD=docker
      - PGHOST=postgis
      - PGPORT=5432
      - PGDATABASE=gis
      - "USGS_DATA_HOST=${USGS_DATA_HOST}"
    volumes:
      - ./data:/src/app/data
    command: all
    depends_on: [postgis]

  triplestore:
    image: bregalia/marmotta
    ports:
      - "5432:5432"
      - "8080:8080"

  importer:
    image: bregalia/kiwi-bulk-loader
    environment:
      - PGUSER=script
      - PGPASSWORD=pass
      - PGHOST=triplestore
      - PGPORT=5432
      - PGDATABASE=kiwi
      - "TRIPLES_BATCH=${TRIPLES_BATCH}"
    volumes:
      - ./data:/src/app/data
    command: all
    depends_on: [triplestore]

  frontend:
    image: bregalia/gnis-ld.org
    ports:
      - "3001:80"
    environment:
      - PGUSER=script
      - PGPASSWORD=pass
      - PGHOST=triplestore
      - PGPORT=5432
      - PGDATABASE=kiwi
      - "USGS_DATA_HOST=${USGS_DATA_HOST}"
      - "USGS_ENDPOINT_URL=http://triplestore:8080/marmotta/sparql/select"
    depends_on: [triplestore]
