version: '3'

services:
  postgis:
    image: kartoza/postgis:10.0-2.4

  triplifier:
    image: bregalia/usgs-triplifier
    environment:
      - PGUSER=docker
      - PGPASSWORD=docker
      - PGHOST=postgis
      - PGPORT=5432
      - PGDATABASE=gis
    volumes:
      - ./data:/src/app/data
    command: all
    depends_on: [postgis]

  triplestore:
    image: bregalia/marmotta
    ports:
      - "8080:8080"

  importer:
    image: bregalia/kiwi-bulk-importer
    environment:
      - PGUSER=script
      - PGPASSWORD=pass
      - PGHOST=triplestore
      - PGPORT=5432
      - PGDATABASE=kiwi
    volumes:
      - ./data:/src/app/data
    command: all
    depends_on: [triplestore]

  frontend:
    image: bregalia/gnis-ld.org
    ports:
      - "3001:80"
    environment:
      - PGUSER=script
      - PGPASSWORD=pass
      - PGHOST=triplestore
      - PGPORT=5432
      - PGDATABASE=kiwi
      - "USGS_ENDPOINT_URL=http://triplestore:8080/marmotta/sparql/select"
    depends_on: [triplestore]
